# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.15.1
_src_path: git+https://github.com/oca/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env:
    PIP_EXTRA_INDEX_URL: https://wheelhouse.shopinvader.com/simple/
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: false
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 14.0
org_name: Shopinvader
org_slug: shopinvader
rebel_module_groups: []
repo_description: Payment methods for Odoo Shopinvader
repo_name: Shopinvader payment modules
repo_slug: odoo-shopinvader-payment
repo_website: https://github.com/shopinvader/odoo-shopinvader-payment
travis_apt_packages: []
travis_apt_sources: []

