exclude: >
  (?x)(
    ^setup/|
    /cassettes/|
    \.pot$|
    \.po$|
    /README.rst$|
    ^(
      # installable = False
      shopinvader_locomotive_payment_adyen|
      shopinvader_payment_adyen|
      shopinvader_payment_paypal
    )/
  )
default_language_version:
  python: python3
repos:
- repo: https://github.com/ambv/black
  rev: 18.9b0
  hooks:
  - id: black
    args: [--line-length=79, --safe]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
  - id: fix-encoding-pragma
    args: ["--remove"]
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8
    name: flake8 except __init__.py
    args: [--exclude=__init__.py]
  - id: flake8
    name: flake8 only __init__.py
    args: [--extend-ignore=F401]  # ignore imported unused in __init__.py
    files: __init__.py
- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v2.3.0
  hooks:
    - id: pylint
      args: ["--rcfile=.pylintrc"]
      additional_dependencies: ["pylint-odoo==3.1.0"]
- repo: https://github.com/asottile/pyupgrade
  rev: v1.6.1
  hooks:
  - id: pyupgrade
- repo: https://github.com/asottile/seed-isort-config
  rev: v1.3.0
  hooks:
  - id: seed-isort-config
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
  - id: isort
